---
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.ya?ml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor != 'renovate[bot]' }}
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        timeout-minutes: 3
        with:
          aqua_version: v2.51.2
      - name: Actionlint
        run: |
          actionlint
