---
name: lint
on:
  workflow_call:
jobs:
  changed-files:
    # Get changed files to filter jobs
    outputs:
      yamlfmt: ${{ steps.changes.outputs.yamlfmt_any_changed == 'true' }}
      renovate: ${{ steps.changes.outputs.renovate_any_changed == 'true' }}
      deno: ${{ steps.changes.outputs.deno_any_changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    steps:
      - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        id: changes
        timeout-minutes: 3
        with:
          files_yaml: |
            yamlfmt:
              - '**.yml'
              - '**.yaml'
            renovate:
              - 'renovate.json'
            deno:
              - '**.ts'
              - 'deno.lock'
  typos:
    name: "Typos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        timeout-minutes: 3
        with:
          aqua_version: v2.53.3
      - name: typos
        timeout-minutes: 3
        run: |
          typos --config .typos.toml .
  secret:
    name: "Secret Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        timeout-minutes: 3
        with:
          aqua_version: v2.53.3
      - name: trivy
        timeout-minutes: 3
        run: |
          trivy fs \
            --scanners secret \
            --severity MEDIUM,HIGH,CRITICAL \
            --exit-code 1 \
            .
  yamlfmt:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.yamlfmt == 'true' && github.actor != 'renovate[bot]' }}
    name: "Yaml"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        timeout-minutes: 3
        with:
          aqua_version: v2.53.3
      - name: yamlfmt
        timeout-minutes: 3
        run: |
          yamlfmt -lint .
  renovate:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.renovate == 'true' && github.actor != 'renovate[bot]' }}
    name: "Renovate validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
        with:
          strict: "true"
  deno:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.deno == 'true' }}
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        timeout-minutes: 3
        with:
          aqua_version: v2.53.3
      - name: fmt
        run: deno fmt --check
      - name: lint
        run: deno lint
#      - name: test
#        run: deno test --allow-all
#      - name: trivy
#        run: trivy fs deno.lock
